version: '3.8'

services:
  ecc_frontend:
    build:
      context: ./ecc_frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ecc_api:
    build:
      context: ./ecc_api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
