# Generated by Django 4.2.6 on 2023-10-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productOwnerName', models.CharField(max_length=255)),
                ('scrumMasterName', models.CharField(max_length=255)),
                ('developers', models.JSONField()),
                ('startDate', models.DateField()),
                ('methodology', models.CharField(max_length=255)),
                ('location', models.URLField()),
            ],
        ),
    ]
