# Generated by Django 4.2.6 on 2023-10-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
